services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build:
      context: ./employee-frontend
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:80"
    depends_on:
      - backend